apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: icgroup
type: Opaque
data:
  pgadmin-email: dnNyaXRoYXJhbkBteWdlcy5mcg==  # vsritharan@myges.fr
  pgadmin-password: YWRtaW4xMjM=               # admin123
  postgres-password: b2Rvbw==               # mypostgres
  odoo-password: b2Rvbw==                       # odoo
