apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
        - name: ic-webapp
          image: vaksalan25/ic-webapp:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ODOO_URL
              value: http://odoo:8069
            - name: PGADMIN_URL
              value: http://pgadmin:80
---
apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    env: prod
spec:
  type: NodePort
  selector:
    app: ic-webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
